[phases.setup]
nixPkgs = ["python3", "gcc", "pkg-config", "mariadb-connector-c", "mariadb-connector-c.dev"]

[variables]
PKG_CONFIG_PATH = "/root/.nix-profile/lib/pkgconfig:/root/.nix-profile/share/pkgconfig"
