# Generated by Django 5.2.1 on 2025-07-14 16:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa_eleitoral', '0002_alter_dadoeleitoral_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug do Artigo')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('total_views', models.PositiveIntegerField(default=0, verbose_name='Total de Visualizações')),
            ],
            options={
                'verbose_name': 'Artigo do Blog',
                'verbose_name_plural': 'Artigos do Blog',
                'db_table': 'blog_articles',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['slug'], name='idx_blog_slug'), models.Index(fields=['total_views'], name='idx_blog_views'), models.Index(fields=['is_active', 'total_views'], name='idx_active_views')],
            },
        ),
        migrations.CreateModel(
            name='BlogArticleView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Visualização')),
                ('ip_address', models.CharField(blank=True, max_length=15, null=True, verbose_name='IP Address')),
                ('user_agent', models.CharField(blank=True, max_length=200, null=True, verbose_name='User Agent')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='mapa_eleitoral.blogarticle')),
            ],
            options={
                'verbose_name': 'Visualização de Artigo',
                'verbose_name_plural': 'Visualizações de Artigos',
                'db_table': 'blog_article_views',
                'indexes': [models.Index(fields=['article', 'viewed_at'], name='idx_article_date'), models.Index(fields=['viewed_at'], name='idx_view_date'), models.Index(fields=['ip_address', 'viewed_at'], name='idx_ip_date')],
            },
        ),
    ]
