# Generated by Django 5.2.1 on 2025-07-03 02:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEFI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=200, verbose_name='Client ID')),
                ('client_secret', models.CharField(max_length=200, verbose_name='Client Secret')),
                ('certificate_path', models.CharField(max_length=500, verbose_name='Caminho do Certificado')),
                ('sandbox', models.BooleanField(default=True, verbose_name='Modo Sandbox')),
                ('webhook_url', models.URLField(blank=True, verbose_name='URL do Webhook')),
                ('ativa', models.BooleanField(default=True, verbose_name='Configuração Ativa')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Configuração EFI Bank',
                'verbose_name_plural': 'Configurações EFI Bank',
            },
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_doador', models.CharField(max_length=100, verbose_name='Nome do Doador')),
                ('email_doador', models.EmailField(max_length=254, verbose_name='Email do Doador')),
                ('telefone_doador', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('cpf_doador', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Doação')),
                ('tipo_pagamento', models.CharField(choices=[('pix', 'PIX'), ('cartao', 'Cartão de Crédito'), ('boleto', 'Boleto')], max_length=20, verbose_name='Tipo de Pagamento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='Status')),
                ('efi_transaction_id', models.CharField(blank=True, max_length=100, verbose_name='ID Transação EFI')),
                ('efi_charge_id', models.CharField(blank=True, max_length=100, verbose_name='ID Cobrança EFI')),
                ('efi_qr_code', models.TextField(blank=True, verbose_name='QR Code PIX')),
                ('efi_qr_code_image', models.URLField(blank=True, verbose_name='Imagem QR Code')),
                ('efi_copy_paste', models.TextField(blank=True, verbose_name='Código PIX Copia e Cola')),
                ('mensagem', models.TextField(blank=True, verbose_name='Mensagem do Doador')),
                ('anonimo', models.BooleanField(default=False, verbose_name='Doação Anônima')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('data_pagamento', models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento')),
            ],
            options={
                'verbose_name': 'Doação',
                'verbose_name_plural': 'Doações',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='LogTransacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=100, verbose_name='Evento')),
                ('dados', models.JSONField(verbose_name='Dados da Transação')),
                ('resposta_efi', models.JSONField(blank=True, null=True, verbose_name='Resposta EFI')),
                ('sucesso', models.BooleanField(default=True, verbose_name='Sucesso')),
                ('erro', models.TextField(blank=True, verbose_name='Erro')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('doacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='doacoes.doacao')),
            ],
            options={
                'verbose_name': 'Log de Transação',
                'verbose_name_plural': 'Logs de Transações',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
